"""
MITRE ATT&CK Navigator Layer Exporter.
Outputs a layer JSON you can import at https://mitre-attack.github.io/attack-navigator/
"""
import json, sys

def export_layer(techniques: list, name: str = "Blaakpearl Portfolio") -> dict:
    TACTIC_COLORS = {
        "Initial Access":"#ff4757","Execution":"#ff6b81","Persistence":"#ffa502",
        "Privilege Escalation":"#ffb700","Defense Evasion":"#eccc68",
        "Credential Access":"#a29bfe","Discovery":"#00d4ff",
        "Lateral Movement":"#55efc4","Collection":"#81ecec",
        "Command and Control":"#fd79a8","Exfiltration":"#e17055","Impact":"#d63031"
    }
    return {
        "name": name, "versions":{"attack":"14","navigator":"4.9"},
        "domain":"enterprise-attack",
        "description": f"{name} — generated by Blaakpearl security portfolio tooling",
        "techniques": [{"techniqueID": t["id"], "score": 100,
                         "color": TACTIC_COLORS.get(t.get("tactic",""),"#636e72"),
                         "comment": t.get("note",""), "enabled": True} for t in techniques],
        "showTacticRowBackground": True, "tacticRowBackground":"#0f1318"
    }

if __name__ == "__main__":
    sample_techniques = [
        {"id":"T1566.001","tactic":"Initial Access","note":"Spearphishing with .docm attachment"},
        {"id":"T1059.001","tactic":"Execution","note":"PowerShell download cradle"},
        {"id":"T1547.001","tactic":"Persistence","note":"Registry Run key"},
        {"id":"T1071.004","tactic":"Command and Control","note":"DNS beaconing at 60s intervals"},
    ]
    print(json.dumps(export_layer(sample_techniques), indent=2))
